backend/modules/apple/controllers/DefaultController.php
<?php

namespace backend\modules\apple\controllers;

use backend\modules\apple\classes\AppleFaker;
use backend\modules\apple\classes\AppleFallen;
use backend\modules\apple\classes\AppleModel;
use backend\modules\apple\classes\AppleOnTree;
use common\components\AppleFakerBehavior;
use common\models\Apple;
use common\models\AppleSearch;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Default controller for the `apple` module
 */
class DefaultController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'example' => [
                'class' => AppleFakerBehavior::class,
            ]
        ];
    }

    /**
     * Lists all Apple models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AppleSearch();
        $dataProvider = $searchModel->search(app()->request->queryParams);

        /*$model = new AppleFaker();
        dd($model->setStatusAppleFaker());*/

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Generate multiple Apple's models. Before clean old models
     * @param int $times
     * @return Response
     */
    public function actionGenerate($times = 1)
    {
        $appleFaker = new AppleFaker();
        $appleFaker->cleanAppleTable()->run($times);

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return Response
     */
    public function actionEat($id)
    {
        $model = AppleFallen::findOne($id);

        try {
            $result = $model->tryToEat();
            app()->session->setFlash('success', $result);
        } catch (\Exception $e) {
            app()->session->setFlash('danger',$e->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return Response
     */
    public function actionFall($id)
    {
        $model = AppleOnTree::findOne($id);

        try {
            $result = $model->fallToGround();
            app()->session->setFlash('success', $result);
        } catch (\Exception $e) {
            app()->session->setFlash('danger',$e->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Apple model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->softDelete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Apple model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Apple the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Apple::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/modules/apple/views/default/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Apple */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="apple-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'color')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'fall_datetime')->textInput() ?>

    <?= $form->field($model, 'make_datetime')->textInput() ?>

    <?= $form->field($model, 'eat')->textInput() ?>

    <?= $form->field($model, 'size')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/apple/views/default/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\AppleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="apple-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'color') ?>

    <?= $form->field($model, 'fall_datetime') ?>

    <?php // echo $form->field($model, 'make_datetime') ?>

    <?php // echo $form->field($model, 'eat') ?>

    <?php // echo $form->field($model, 'size') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/apple/views/default/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Apple */

$this->title = 'Create Apple';
$this->params['breadcrumbs'][] = ['label' => 'Apples', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="apple-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/apple/views/default/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\AppleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Apples';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="apple-index">

    <?= $this->render('//widgets/alert') ?>

    <p>
        <?= Html::a('Generate 10 apples', ['default/generate', 'times' => 10], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Generate 20 apples', ['default/generate', 'times' => 20], ['class' => 'btn btn-info']) ?>
        <?= Html::a('Generate 30 apples', ['default/generate', 'times' => 30], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Generate 40 apples', ['default/generate', 'times' => 40], ['class' => 'btn btn-warning']) ?>
        <?= Html::a('Generate 50 apples', ['default/generate', 'times' => 50], ['class' => 'btn btn-danger']) ?>
    </p>

    <p class="bg-info">
        При кусании откусывается, если есть возможность то всегда на 25%
        <br>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'user_id',
                'value' => function($model) {
                    return $model->user->username;
                },
            ],
            'status',
            'color',
            'fall_datetime',
            'make_datetime',
            'eat',
            'size',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Действия',
                'headerOptions' => ['width' => '200'],
                'template' => '<div class="text-center">{eat} {fall} {delete}</div></div> ',
                'buttons' => [
                    'eat' => function ($url,$model) {
                        return Html::a($model->eatButtonTitle,
                            ['eat', 'id' => $model->id],
                            ['class' => 'btn btn-xs btn-success' . $model->eatButtonAccess]
                        );
                    },
                    'fall' => function ($url,$model) {
                        return Html::a($model->fallButtonTitle,
                            ['fall', 'id' => $model->id],
                            ['class' => 'btn btn-xs btn-warning' . $model->fallButtonAccess]
                        );
                    },
                    'delete' => function ($url, $model, $key) {
                        $options = array_merge([
                            'class' => 'btn btn-xs btn-danger' . $model->removeButtonAccess,
                            'title' => Yii::t('yii', 'Delete'),
                            'aria-label' => Yii::t('yii', 'Delete'),
                            'data-confirm' => Yii::t('yii', 'Вы уверены что хотите удалить '.$model->id.'е яблоко ?'),
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ]);
                        return Html::a('Удалить', $url, $options);
                    },
                ],
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

backend/modules/apple/views/default/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Apple */

$this->title = 'Update Apple: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Apples', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="apple-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/apple/views/default/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Apple */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Apples', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="apple-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'status',
            'color',
            'fall_datetime',
            'make_datetime',
            'eat',
            'size',
        ],
    ]) ?>

</div>